project:
  name: sigmaranks
  timezone: America/New_York
data:
  raw_dir: data/raw
  interim_dir: data/interim
  processed_dir: data/processed
fetch:
  days: 756
  lookback_period: 90d
  number: 50
  tickers:
  - TSLA
  - NVDA
  - AAPL
  - MSFT
  - META
  - AMD
  - AMZN
  - GOOGL
  - AVGO
  - PLTR
  - ORCL
  - GOOG
  - MU
  - NFLX
  - HOOD
  - APP
  - INTC
  - LLY
  - UNH
  - COIN
  - JPM
  - COST
  - BRK-B
  - CRM
  - V
  - WMT
  - GEV
  - BAC
  - AMAT
  - XOM
  - SNDK
  - BA
  - JNJ
  - UBER
  - LRCX
  - QCOM
  - GS
  - MA
  - PFE
  - ADBE
  - HD
  - CSCO
  - CAT
  - NOW
  - IBM
  - C
  - CRWD
  - TXN
  - BKNG
  - INTU
